### ISSUE TITLE
어떤 게임을 만들어볼까요?

### ISSUE THREAD

**Issue by publdaze** [KEEPER31337/ReactStudy#34]

**Comment by publdaze** [comment]
- 이전 홈페이지에서 있던 게임 만든다.

**Comment by publdaze** [comment]
- 다른 게임 만든다.

**Comment by publdaze** [comment]
이론만 공부한다.
-> 전체 범위 나가기

**Comment by publdaze** [comment]
게임 프로젝트도 하는 경우
위로 따봉 - 전체 범위
아래로 따봉 - Adding Interactivity 까지

**Comment by publdaze** [comment]
Adding Interactivity 까지로 땅땅땅!

**Comment by publdaze** [comment]
yachu

**Comment by publdaze** [comment]
숫자 야구 게임 (몇 턴만에 맞췄는 지에 따라 획득 포인트 다르게 주기)
참고 - https://github.com/woowacourse-precourse/javascript-baseball

**Comment by publdaze** [comment]
지뢰 찾기
참고 - https://github.com/minsgy/minesweeper_web_game

**Comment by jasper200207** [comment]
주식

**Comment by pipisebastian** [comment]
벽돌깨기

**Comment by pipisebastian** [comment]
플래피 버드

**Comment by KimHaejoong1** [comment]
스테이지 누적될수록 점점 빨라지는 야바위

**Comment by publdaze** [comment]
테트리스 (점점 빨라지게)

**Comment by pipisebastian** [comment]
무한의 계단

**Comment by KimHaejoong1** [comment]
크롬 공룡게임

**Comment by KimHaejoong1** [comment]
가위바위보 하나빼기

**Comment by pipisebastian** [comment]
[검 강화하기](https://vidkidz.tistory.com/5291)

**Comment by yessjun** [comment]
같은 카드 찾기

**Comment by publdaze** [comment]
** 의견 남기는 중~ **

숫자 야구 게임
- 참고할 만한 게 많음 별도의 assets 딱히 필요없음

지뢰 찾기
- 알고리즘... 복잡할듯

플래피 버드
- asset 많이 필요할 것 같고, 참고할 만한게 많지 않은 듯

야바위
- 특정 컵?을 위치는 변경시키면서 최종 위치를 파악하도록 하는 로직을 잘 적용할 수 있을 지는 모르겠지만 괜찮을지도?
- 참고 - https://coronasdk.tistory.com/110

테트리스
- 별도 asset 딱히 필요 없을 듯
- 참고 - https://velog.io/@app235naver/React-%ED%85%8C%ED%8A%B8%EB%A6%AC%EC%8A%A4-%EB%A7%8C%EB%93%A4%EA%B8%B0

무한의 계단
- 뒤에 배경 안 변하면 재미 없을 것 같기도?
- 하지만 배경 있으려면 그려야 함..!
- 계단 배치도 반복적이지 않도록 해야 함

가위바위보 하나빼기
- 간단하게 구현 가능할 듯

같은 카드 찾기
- 배치 로직 백엔드 쪽으로 넘겨버리면 구현 간단할 듯
- 참고 - https://dororongju.tistory.com/103

사과게임
- 드래그 해서 잡은 범위 만큼의 숫자를 인식해서 더한 값을 얻는 과정이 조금 복잡하지 않을까..

**Comment by KimHaejoong1** [comment]
https://www.gamesaien.com/game/fruit_box_a/
사과게임 ?

**Comment by pipisebastian** [comment]
야바위 추천해요~!~
1. [예시 링크](https://github.com/rpemberton/shell-game )
2. 장점 : 길면 사람들이 안하는데, 아주 짧게 끝남
3. 링크처럼, 꼭 컵과 공이 아니어도 좋을듯! 예를 들어 저금통안에 동전 숨기기!
4. 단점 : 너무 간단할지도!


![Image](https://user-images.githubusercontent.com/81643702/235096087-c0908f0d-25e4-47aa-9c58-e48e866c0f3b.png)

**Comment by KimHaejoong1** [comment]
순서대로 숫자 누르기
http://zzzscore.com/1to50/?from=kt

**Comment by KimHaejoong1** [comment]
뱀 게임
https://snake.googlemaps.com/?hl=ko

**Comment by publdaze** [comment]
야바위 땅땅땅
