### ISSUE TITLE
react 공부 정리 및 발표 자료 준비

### ISSUE THREAD

**Issue by sososo0** [KEEPER31337/ReactStudy#7]

**Comment by publdaze** [comment]
[docs : installation 정리](https://github.com/KEEPER31337/ReactStudy/commit/a74f91e169782a18bbb6a58abc7b5bfc4a4cb1d0)
[docs : installation 정리](https://github.com/KEEPER31337/ReactStudy/commit/daf816708c2c17f96fbbdfe3b02a30b40a29610f)
[docs : installation 정리](https://github.com/KEEPER31337/ReactStudy/commit/024dcb2075cf6d51682523ee2914e4fb28ab4d39)
